import { Employee, Attendance, LeaveRequest, Payroll, Performance, Department, Document } from '@/types';

export const mockEmployees: Employee[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@company.com',
    phone: '+1 234 567 8901',
    position: 'Senior Software Engineer',
    department: 'Engineering',
    salary: 95000,
    joinDate: '2021-03-15',
    status: 'active',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
  },
  {
    id: '2',
    name: 'Michael Chen',
    email: 'michael.chen@company.com',
    phone: '+1 234 567 8902',
    position: 'Product Manager',
    department: 'Product',
    salary: 105000,
    joinDate: '2020-07-01',
    status: 'active',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael',
  },
  {
    id: '3',
    name: 'Emily Rodriguez',
    email: 'emily.rodriguez@company.com',
    phone: '+1 234 567 8903',
    position: 'UX Designer',
    department: 'Design',
    salary: 82000,
    joinDate: '2022-01-10',
    status: 'active',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily',
  },
  {
    id: '4',
    name: 'David Kumar',
    email: 'david.kumar@company.com',
    phone: '+1 234 567 8904',
    position: 'HR Manager',
    department: 'Human Resources',
    salary: 78000,
    joinDate: '2019-11-20',
    status: 'active',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
  },
  {
    id: '5',
    name: 'Lisa Anderson',
    email: 'lisa.anderson@company.com',
    phone: '+1 234 567 8905',
    position: 'Marketing Director',
    department: 'Marketing',
    salary: 98000,
    joinDate: '2020-04-12',
    status: 'on_leave',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa',
  },
];

export const mockAttendance: Attendance[] = [
  {
    id: '1',
    employeeId: '1',
    date: '2025-01-10',
    checkIn: '09:00',
    checkOut: '18:00',
    status: 'present',
    hoursWorked: 9,
  },
  {
    id: '2',
    employeeId: '2',
    date: '2025-01-10',
    checkIn: '08:45',
    checkOut: '17:45',
    status: 'present',
    hoursWorked: 9,
  },
  {
    id: '3',
    employeeId: '3',
    date: '2025-01-10',
    checkIn: '09:15',
    status: 'present',
  },
  {
    id: '4',
    employeeId: '4',
    date: '2025-01-10',
    checkIn: '09:00',
    checkOut: '18:00',
    status: 'present',
    hoursWorked: 9,
  },
  {
    id: '5',
    employeeId: '5',
    date: '2025-01-10',
    status: 'on_leave',
  },
];

export const mockLeaveRequests: LeaveRequest[] = [
  {
    id: '1',
    employeeId: '1',
    employeeName: 'Sarah Johnson',
    type: 'vacation',
    startDate: '2025-01-20',
    endDate: '2025-01-25',
    reason: 'Family vacation',
    status: 'pending',
  },
  {
    id: '2',
    employeeId: '5',
    employeeName: 'Lisa Anderson',
    type: 'sick',
    startDate: '2025-01-08',
    endDate: '2025-01-12',
    reason: 'Medical treatment',
    status: 'approved',
    approvedBy: 'David Kumar',
    approvedAt: '2025-01-07',
  },
  {
    id: '3',
    employeeId: '3',
    employeeName: 'Emily Rodriguez',
    type: 'casual',
    startDate: '2025-01-15',
    endDate: '2025-01-15',
    reason: 'Personal matters',
    status: 'approved',
    approvedBy: 'David Kumar',
    approvedAt: '2025-01-10',
  },
];

export const mockPayroll: Payroll[] = [
  {
    id: '1',
    employeeId: '1',
    employeeName: 'Sarah Johnson',
    month: '2025-01',
    basicSalary: 95000,
    allowances: 5000,
    deductions: 12000,
    netSalary: 88000,
    status: 'processed',
  },
  {
    id: '2',
    employeeId: '2',
    employeeName: 'Michael Chen',
    month: '2025-01',
    basicSalary: 105000,
    allowances: 6000,
    deductions: 14000,
    netSalary: 97000,
    status: 'processed',
  },
  {
    id: '3',
    employeeId: '3',
    employeeName: 'Emily Rodriguez',
    month: '2025-01',
    basicSalary: 82000,
    allowances: 4000,
    deductions: 10000,
    netSalary: 76000,
    status: 'pending',
  },
];

export const mockPerformance: Performance[] = [
  {
    id: '1',
    employeeId: '1',
    employeeName: 'Sarah Johnson',
    reviewPeriod: 'Q4 2024',
    overallRating: 4.5,
    goals: [
      {
        id: '1',
        title: 'Complete feature migration',
        description: 'Migrate legacy features to new architecture',
        target: 100,
        achieved: 95,
        status: 'on_track',
      },
      {
        id: '2',
        title: 'Mentor junior developers',
        description: 'Provide guidance to 2 junior team members',
        target: 100,
        achieved: 100,
        status: 'completed',
      },
    ],
    feedback: 'Excellent performance with strong technical leadership',
    reviewerId: '2',
    reviewDate: '2025-01-05',
  },
  {
    id: '2',
    employeeId: '3',
    employeeName: 'Emily Rodriguez',
    reviewPeriod: 'Q4 2024',
    overallRating: 4.2,
    goals: [
      {
        id: '3',
        title: 'Redesign user dashboard',
        description: 'Create new user-friendly dashboard design',
        target: 100,
        achieved: 100,
        status: 'completed',
      },
    ],
    feedback: 'Great design work with attention to user experience',
    reviewerId: '2',
    reviewDate: '2025-01-06',
  },
];

export const mockDepartments: Department[] = [
  {
    id: '1',
    name: 'Engineering',
    headId: '1',
    headName: 'Sarah Johnson',
    employeeCount: 45,
    budget: 4500000,
  },
  {
    id: '2',
    name: 'Product',
    headId: '2',
    headName: 'Michael Chen',
    employeeCount: 12,
    budget: 1200000,
  },
  {
    id: '3',
    name: 'Design',
    headId: '3',
    headName: 'Emily Rodriguez',
    employeeCount: 8,
    budget: 650000,
  },
  {
    id: '4',
    name: 'Human Resources',
    headId: '4',
    headName: 'David Kumar',
    employeeCount: 6,
    budget: 450000,
  },
  {
    id: '5',
    name: 'Marketing',
    headId: '5',
    headName: 'Lisa Anderson',
    employeeCount: 15,
    budget: 1500000,
  },
];

export const mockDocuments: Document[] = [
  {
    id: '1',
    employeeId: '1',
    name: 'Employment Contract',
    type: 'PDF',
    uploadDate: '2021-03-15',
    size: '2.4 MB',
    url: '#',
  },
  {
    id: '2',
    employeeId: '1',
    name: 'Tax Documents 2024',
    type: 'PDF',
    uploadDate: '2024-12-01',
    size: '1.8 MB',
    url: '#',
  },
  {
    id: '3',
    employeeId: '2',
    name: 'Performance Review Q4',
    type: 'PDF',
    uploadDate: '2025-01-05',
    size: '850 KB',
    url: '#',
  },
];
